### ISSUE TITLE
Getting errors when running on aws docker ec2

### ISSUE THREAD

**Issue by RickardRanniger** [ftpgrab/docker#4]
It works fine locally in Docker for mac but on Amazon EC2 docker image I get 
`"ftpgrab    | Cannot make/remove an entry for the specified session"`
in the logs with the exact same setup.

**Comment by crazy-max** [comment]
@RickardRanniger Ok thanks for your input, this will be solved on the next major release (see ftpgrab/ftpgrab#36)

**Comment by crazy-max** [comment]
@RickardRanniger It seems it's an issue with the debian layer. Can you pull the latest tag and try again ?
